theme: jekyll-theme-leap-day
project_title: The FrameIT Project
project_tagline: Detangling Knowledge Management from Game Design in Serious Games
description: The FrameIT Project — Detangling Knowledge Management from Game Design in Serious Games
logo: ./img/frameworld-1-screenshot.png
